server:
  port: 8080

spring:
  application:
    name: netty-chat
  profiles:
    active: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/netty?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver


# mybatis 配置内容
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.qhkj.nettychatserver
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_


netty:
  read.time: 60
  write.time: 10
  readAndWrite: 0